"""Data-driven KiCad schematic generator (Stage 6 engine).

Builds a .kicad_sch from three data files — with every fact having exactly one home:

  * netlist YAML (Stage 5b)  -> connectivity + each component's pin-number set
  * BOM flat markdown (Stage 3) -> value + footprint (joined on reference)
  * layout YAML (Stage 6)    -> placement (x/y/rotation) + IC pin-side arrangement

Nothing is retyped: footprints/values come only from the BOM, connectivity only
from the netlist. The engine is a pure function of its inputs (no KiCad install,
no network) and self-verifies before saving — it runs the structural validator,
the netlist verifier, and the BOM cross-check in-process and refuses to emit a
file with errors. A pin assigned to net Y but drawn onto net X (the J3 short
class) is therefore caught at generation time, not after fabrication.

CLI:
    python generate_from_data.py <netlist.yaml> <bom.md> <layout.yaml> \
        -o out.kicad_sch [--strict] [--uuid-seed N] [--json]
"""

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Make sibling skill modules importable whether run as a script or imported.
sys.path.insert(0, str(Path(__file__).resolve().parent))

import yaml

from generate_kicad_sch import KicadSchematic
from verify_netlist import (
    IntendedNetlist, load_intended_netlist, load_intended_netlist_from_string,
    verify,
)
from cross_check_bom import load_bom_from_markdown, cross_check
from validate_kicad_sch import validate
from check_pcbway import (
    CANONICAL_MPN_FIELD, CANONICAL_PACKAGE_FIELD,
    looks_like_distributor_code, looks_like_description,
)


# Placeholder tokens that mean "no value" in a BOM cell.
_BLANK_TOKENS = {"", "-", "—", "–", "n/a", "tbd"}


def _blank(s):
    """Normalize BOM placeholder dashes / TBD to empty string."""
    return "" if (s or "").strip().lower() in _BLANK_TOKENS else (s or "").strip()


def _real_mpn(part_number):
    """The part number iff it is a *real* manufacturer PN — never a distributor
    catalog code (LCSC C#####) or a description ('56k 5% 0805'), which would
    silently poison the PCBway BOM's MPN column. Returns "" otherwise."""
    pn = _blank(part_number)
    if not pn or looks_like_distributor_code(pn) or looks_like_description(pn):
        return ""
    return pn


def _pcbway_symbol_props(bom):
    """Build the PCBway identity fields to bake onto a placed symbol from its BOM
    line. Emits exactly one mpn-family key (only when the PN is real), so the plugin
    never reads an empty/shadowed MPN. See check_pcbway's field-name contract."""
    extra = {}
    mpn = _real_mpn(getattr(bom, "part_number", ""))
    if mpn:
        extra[CANONICAL_MPN_FIELD] = mpn
    mfr = _blank(getattr(bom, "manufacturer", ""))
    if mfr:
        extra["Manufacturer"] = mfr
    pkg = _blank(getattr(bom, "package", "")) or _blank(bom.footprint)
    if pkg:
        extra[CANONICAL_PACKAGE_FIELD] = pkg
    desc = _blank(getattr(bom, "description", ""))
    if desc:
        extra["Description"] = desc
    supplier = _blank(getattr(bom, "supplier", ""))
    supplier_pn = _blank(getattr(bom, "supplier_pn", ""))
    if supplier.upper().startswith("LCSC") and supplier_pn:
        # Optional JLCPCB-toolkit dual-compat field — never the only PN field.
        extra["LCSC Part #"] = supplier_pn
    return extra


# ─── lib_id → symbol dispatch ────────────────────────────────────────
# Passives/standard parts whose symbol is generated by a no-arg helper.
PASSIVE_DISPATCH = {
    "Device:R": "add_lib_symbol_resistor",
    "Device:C": "add_lib_symbol_capacitor",
    "Device:C_Polarized": "add_lib_symbol_capacitor_polarized",
    "Device:L": "add_lib_symbol_inductor",
    "Device:LED": "add_lib_symbol_led",
    "Device:D": "add_lib_symbol_diode",
    "Device:Q_NMOS_GSD": "add_lib_symbol_mosfet_n",
    "Device:Q_PMOS_GSD": "add_lib_symbol_mosfet_p",
    "Device:Q_NPN_BCE": "add_lib_symbol_bjt_npn",
    "Device:Q_PNP_BCE": "add_lib_symbol_bjt_pnp",
    "Device:Crystal": "add_lib_symbol_crystal",
    "Device:Crystal_GND24": "add_lib_symbol_crystal_4pin",
}
_CONN_RE = re.compile(r"^Connector_Generic:Conn_01x(\d+)$")


# ─── Layout dataclasses ──────────────────────────────────────────────
@dataclass
class Placement:
    ref: str
    lib_id: str
    x: float
    y: float
    rotation: int = 0


@dataclass
class SymbolDef:
    lib_id: str
    pins: list = field(default_factory=list)  # (number, name, type, side, index)
    ref_prefix: str = "U"
    width: float = 10.16
    from_library: bool = False  # embed the real library symbol verbatim (use as-is)
    block: str = ""             # resolved/inline (symbol ...) s-expr for embedding


@dataclass
class Layout:
    project: str = ""
    title: str = "Untitled"
    rev: str = "1.0"
    power_nets: list = field(default_factory=list)
    placements: dict = field(default_factory=dict)  # ref -> Placement
    symbols: dict = field(default_factory=dict)      # lib_id -> SymbolDef


@dataclass
class GenerateResult:
    passed: bool
    errors: list = field(default_factory=list)
    warnings: list = field(default_factory=list)
    sch: object = None
    output_path: str = None


class EngineError(Exception):
    """Raised when the design data cannot be assembled into a schematic.

    Carries an aggregated list of human-readable messages in .messages.
    """
    def __init__(self, messages):
        self.messages = list(messages)
        super().__init__("\n".join(self.messages))


# ─── Layout loading ──────────────────────────────────────────────────
def _parse_layout(raw: dict) -> Layout:
    lay = Layout(
        project=raw.get("project", ""),
        title=raw.get("title", raw.get("project", "Untitled")),
        rev=str(raw.get("rev", "1.0")),
        power_nets=list(raw.get("power_nets", [])),
    )
    for ref, pl in raw.get("placements", {}).items():
        if "lib_id" not in pl or "x" not in pl or "y" not in pl:
            raise EngineError([f"placement {ref}: requires lib_id, x, y"])
        lay.placements[ref] = Placement(
            ref=ref, lib_id=pl["lib_id"], x=float(pl["x"]), y=float(pl["y"]),
            rotation=int(pl.get("rotation", 0)),
        )
    for lib_id, sym in raw.get("symbols", {}).items():
        pins = [tuple(p) for p in sym.get("pins", [])]
        lay.symbols[lib_id] = SymbolDef(
            lib_id=lib_id, pins=pins,
            ref_prefix=sym.get("ref_prefix", "U"),
            width=float(sym.get("width", 10.16)),
            from_library=bool(sym.get("from_library", False)),
            block=sym.get("block", "") or "",
        )
    return lay


def load_layout(filepath: str) -> Layout:
    with open(filepath, "r", encoding="utf-8") as f:
        return _parse_layout(yaml.safe_load(f))


def load_layout_from_string(text: str) -> Layout:
    return _parse_layout(yaml.safe_load(text))


# ─── Build ───────────────────────────────────────────────────────────
def _preflight(netlist: IntendedNetlist, bom_by_ref: dict, layout: Layout) -> list:
    """Return a list of structural error messages (empty == ok)."""
    errors = []

    # 1+2: parity between netlist components, placements, and BOM lines.
    for ref in netlist.components:
        if ref not in layout.placements:
            errors.append(f"{ref}: in netlist but has no placement in layout YAML")
        if ref not in bom_by_ref:
            errors.append(f"{ref}: in netlist but has no BOM line")
    for ref in layout.placements:
        if ref not in netlist.components:
            errors.append(f"{ref}: placed in layout but not declared in netlist")
    for ref in bom_by_ref:
        if ref not in netlist.components:
            errors.append(f"{ref}: in BOM but not declared in netlist")

    # 3: pin-set cross-check for placed ICs (symbols carry an explicit pin list).
    for ref, pl in layout.placements.items():
        sym = layout.symbols.get(pl.lib_id)
        comp = netlist.components.get(ref)
        if sym is None or comp is None:
            continue
        sym_pins = {str(p[0]) for p in sym.pins}
        net_pins = {str(p) for p in comp.pins}
        if sym_pins != net_pins:
            missing = net_pins - sym_pins
            extra = sym_pins - net_pins
            detail = []
            if missing:
                detail.append(f"missing from symbol: {sorted(missing)}")
            if extra:
                detail.append(f"extra in symbol: {sorted(extra)}")
            errors.append(
                f"{ref} ({pl.lib_id}): symbol pin-set != netlist pin-set "
                f"({'; '.join(detail)})"
            )

    # 4: completeness — every netlist pin in exactly one net or no_connect.
    assigned = {}
    for net_name, net in netlist.nets.items():
        for p in net.pins:
            assigned.setdefault((p.ref, str(p.pin)), []).append(net_name)
    for nc in netlist.no_connects:
        assigned.setdefault((nc.ref, str(nc.pin)), []).append("<no_connect>")
    for ref, comp in netlist.components.items():
        for pin in comp.pins:
            homes = assigned.get((ref, str(pin)), [])
            if len(homes) == 0:
                errors.append(f"{ref}.{pin}: not assigned to any net or no_connect")
            elif len(homes) > 1:
                errors.append(f"{ref}.{pin}: assigned to multiple nets {homes}")

    # 5: internal-supply output shorted to an input rail (the CH224K VDD->VBUS class).
    #    A device's own regulator/LDO OUTPUT pin (type power_out — e.g. an internal
    #    3.3V rail) must not share a net with that SAME device's power-INPUT/supply
    #    pin. Tying an LDO output onto its own supply rail back-drives the regulator:
    #    on the battery_3s board this drew 0.2A of self-heat and browned out PD
    #    negotiation. A schematic can be internally self-consistent yet still contain
    #    this defect, so the pin-side types are the only place to catch it — see
    #    tests/test_generate_from_data.py::test_regulator_output_shorted_to_supply.
    pin_type = {}   # (ref, pin_number) -> lowercased pin type from the layout symbol
    for r, pl in layout.placements.items():
        sym = layout.symbols.get(pl.lib_id)
        if sym is None:
            continue
        for p in sym.pins:
            if len(p) > 2 and p[2]:
                pin_type[(r, str(p[0]))] = str(p[2]).lower()
    for net_name, net in netlist.nets.items():
        by_ref = {}
        for p in net.pins:
            t = pin_type.get((p.ref, str(p.pin)))
            if t:
                by_ref.setdefault(p.ref, []).append((str(p.pin), t))
        for r, pins in by_ref.items():
            outs = [pn for pn, t in pins if t == "power_out"]
            ins = [pn for pn, t in pins if t == "power_in"]
            if outs and ins:
                errors.append(
                    f"{r}: regulator/output pin(s) {outs} shorted to power-input "
                    f"pin(s) {ins} on net '{net_name}' — an internal-supply output "
                    f"tied to a rail (CH224K VDD->VBUS class). Give the output its "
                    f"own net with only a decoupling cap to GND."
                )

    return errors


def _register_symbols(sch: KicadSchematic, layout: Layout):
    """Register every lib_symbol needed by the placements + power symbols."""
    lib_ids = {pl.lib_id for pl in layout.placements.values()}
    for lib_id in sorted(lib_ids):
        if lib_id in PASSIVE_DISPATCH:
            getattr(sch, PASSIVE_DISPATCH[lib_id])()
            continue
        m = _CONN_RE.match(lib_id)
        if m:
            sch.add_lib_symbol_connector(int(m.group(1)), lib_id)
            continue
        sym = layout.symbols.get(lib_id)
        if sym is None:
            raise EngineError([
                f"lib_id '{lib_id}' is not a known passive/connector and has no "
                f"entry in the layout 'symbols:' section (need pins to build it)"
            ])
        if sym.block:
            # Use the real library symbol as-is (drawing + real pin geometry).
            sch.add_lib_symbol_from_block(
                lib_id, sym.block, ref_prefix=sym.ref_prefix,
            )
            continue
        sch.add_lib_symbol_ic(
            lib_id, pins=sym.pins, ref_prefix=sym.ref_prefix,
            value=lib_id.split(":")[-1], width=sym.width,
        )
    # Power symbols used by the wiring loop.
    for name in (["GND"] + list(layout.power_nets)):
        sch.add_lib_symbol_power(name)


def _resolve_library_symbols(layout: Layout, libraries=None):
    """Ensure every ``from_library`` symbol has an embeddable block + real pins.

    Loads each from-library symbol's block from the registered libraries (unless an
    inline ``block:`` was supplied), parses its real pins, and stores both back on
    the SymbolDef so the pin-set gate checks against the *actual* pins. Raises
    EngineError if a block can't be found.
    """
    errors = []
    need_lookup = [s for s in layout.symbols.values()
                   if s.from_library and not s.block]
    if need_lookup and libraries is None:
        try:
            from check_kicad_library import build_library_set
            libraries = build_library_set()
        except Exception as e:  # noqa: BLE001
            raise EngineError([
                f"cannot resolve from_library symbols (no libraries available): {e}"
            ])
    for sym in layout.symbols.values():
        if not sym.from_library:
            continue
        if not sym.block:
            from check_kicad_library import load_symbol_block
            block = load_symbol_block(sym.lib_id, libraries=libraries)
            if not block:
                errors.append(
                    f"{sym.lib_id}: from_library set but no matching symbol in the "
                    f"registered libraries (pass --project-dir/--sym-lib, or install "
                    f"it with the kicad-import-lib skill)"
                )
                continue
            sym.block = block
        # Real pins (number/name/type) for the pin-set gate.
        pins, _gfx, _meta = KicadSchematic.parse_symbol_block(sym.block)
        sym.pins = [(p.number, p.name, p.pin_type) for p in pins]
    if errors:
        raise EngineError(errors)


def build_schematic(netlist: IntendedNetlist, bom_entries: list, layout: Layout,
                    uuid_seed=None, libraries=None) -> KicadSchematic:
    """Assemble a KicadSchematic from the three data sources.

    Raises EngineError (with aggregated messages) on any structural problem.
    Does NOT run the validators — call self_verify() / generate() for that.

    ``libraries`` is an optional check_kicad_library.LibrarySet used to resolve any
    ``from_library`` symbols (parts embedded verbatim from a registered library).
    """
    bom_by_ref = {e.reference: e for e in bom_entries}

    # Resolve embedded library symbols before the gate so it sees their real pins.
    _resolve_library_symbols(layout, libraries)

    errors = _preflight(netlist, bom_by_ref, layout)
    if errors:
        raise EngineError(errors)

    sch = KicadSchematic(layout.title, rev=layout.rev, uuid_seed=uuid_seed)
    _register_symbols(sch, layout)

    # Place components (BOM owns value/footprint + PCBway identity; layout owns
    # geometry). The MPN/Manufacturer/Package/Description fields are baked onto each
    # symbol so the PCBWay KiCad plugin auto-populates a clean BOM after an F8 sync.
    for ref, pl in layout.placements.items():
        bom = bom_by_ref[ref]
        extra = _pcbway_symbol_props(bom)
        sch.place_component(
            pl.lib_id, ref, bom.value, pl.x, pl.y,
            rotation=pl.rotation, footprint=bom.footprint,
            in_bom=not bom.is_mechanical_non_fitted,
            dnp=bool(getattr(bom, "dnp", False)),
            **extra,
        )

    # Netlist-driven label/power wiring.
    power_nets = set(layout.power_nets)
    for net_name, net in netlist.nets.items():
        for p in net.pins:
            ref, pin = p.ref, str(p.pin)
            if net_name == "GND":
                sch.gnd_at_pin(ref, pin)
            elif net_name in power_nets:
                sch.power_at_pin(ref, pin, net_name)
            else:
                sch.label_at_pin(ref, pin, net_name)

    for nc in netlist.no_connects:
        sch.nc_at_pin(nc.ref, str(nc.pin))

    unassigned = sch.ensure_all_pins_assigned()
    if unassigned:
        raise EngineError([f"unassigned pin after build: {u}" for u in unassigned])
    missing_fp = sch.ensure_footprints()
    if missing_fp:
        raise EngineError([f"missing footprint after build: {m}" for m in missing_fp])

    return sch


# ─── Self-verify gate ────────────────────────────────────────────────
# validate() checks that are blocking for engine output even though their default
# severity is "warning". The label-based generator never creates intentional
# T-joints, so a missing junction always means an unintended wire collision (the
# J3 cell-tap-to-GND short class) — it must never ship.
BLOCKING_VALIDATE_CHECKS = {"missing_junction"}


def self_verify(netlist: IntendedNetlist, bom_entries: list, sch: KicadSchematic,
                strict=False):
    """Run all three validators against the built schematic.

    Returns (errors, warnings) as lists of strings.
    """
    errors, warnings = [], []

    vres = validate(sch)
    for i in vres.issues:
        msg = f"[validate:{i.check_name}] {i.message}"
        blocking = i.severity == "error" or i.check_name in BLOCKING_VALIDATE_CHECKS
        (errors if blocking else warnings).append(msg)

    nres = verify(netlist, sch)
    for i in nres.errors:
        errors.append(f"[verify_netlist:{i.check_name}] {i.message}")
    for i in nres.warnings:
        warnings.append(f"[verify_netlist:{i.check_name}] {i.message}")

    cres = cross_check(bom_entries, sch)
    for i in cres.errors:
        errors.append(f"[cross_check_bom:{i.check_name}] {i.message}")
    for i in cres.warnings:
        warnings.append(f"[cross_check_bom:{i.check_name}] {i.message}")

    if strict:
        errors = errors + warnings
        warnings = []
    return errors, warnings


# ─── Top-level orchestration ─────────────────────────────────────────
def generate(netlist_path, bom_path, layout_path, out_path=None,
             uuid_seed=None, strict=False, libraries=None,
             project_dir=None, extra_sym=None) -> GenerateResult:
    """Load the three data files, build, self-verify, and save iff clean.

    For any ``from_library`` symbol, the real library symbol is embedded verbatim;
    pass ``libraries`` (a LibrarySet) or ``project_dir`` / ``extra_sym`` so it can be
    located beyond KiCad's built-ins.
    """
    netlist = load_intended_netlist(netlist_path)
    with open(bom_path, "r", encoding="utf-8") as f:
        bom_entries = load_bom_from_markdown(f.read())
    layout = load_layout(layout_path)

    if libraries is None and (project_dir or extra_sym):
        from check_kicad_library import build_library_set
        libraries = build_library_set(project_dir=project_dir, extra_sym=extra_sym)

    try:
        sch = build_schematic(netlist, bom_entries, layout,
                              uuid_seed=uuid_seed, libraries=libraries)
    except EngineError as e:
        return GenerateResult(passed=False, errors=e.messages, warnings=[], sch=None)

    errors, warnings = self_verify(netlist, bom_entries, sch, strict=strict)
    result = GenerateResult(passed=not errors, errors=errors, warnings=warnings, sch=sch)

    if not errors and out_path:
        sch.save(out_path)
        result.output_path = out_path
    return result


# Printed after a successful save. The baked MPN/Manufacturer fields live on the
# schematic symbols; they only reach the board (and thus the PCBWay plugin's BOM)
# after an F8 sync — which this skill cannot automate, so it must be said out loud.
PCBWAY_HANDOFF_NOTE = (
    "\nBefore running the PCBWay plugin:\n"
    "  1. Open the PCB and run Update PCB from Schematic (F8) with 'Update footprint\n"
    "     fields' enabled — this carries MPN/Manufacturer/Package onto the board.\n"
    "     No schematic field reaches the BOM without this sync.\n"
    "  2. Set the drill/place origin (the plugin plots pick-and-place relative to it).\n"
    "  3. Then click the PCBWay plugin to generate the BOM + fab files."
)


def _main(argv=None):
    ap = argparse.ArgumentParser(description="Data-driven KiCad schematic generator.")
    ap.add_argument("netlist", help="Stage 5b netlist YAML")
    ap.add_argument("bom", help="Stage 3 BOM markdown (flat table)")
    ap.add_argument("layout", help="Stage 6 layout YAML")
    ap.add_argument("-o", "--output", help="output .kicad_sch path")
    ap.add_argument("--strict", action="store_true", help="treat warnings as errors")
    ap.add_argument("--uuid-seed", type=int, default=None,
                    help="seed UUIDs for reproducible output")
    ap.add_argument("--project-dir",
                    help="project dir whose lib-table to search for from_library symbols")
    ap.add_argument("--sym-lib", action="append", metavar="[NICK=]PATH",
                    help="extra symbol library for from_library symbols; repeatable")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    args = ap.parse_args(argv)

    res = generate(args.netlist, args.bom, args.layout, out_path=args.output,
                   uuid_seed=args.uuid_seed, strict=args.strict,
                   project_dir=args.project_dir, extra_sym=args.sym_lib)

    if args.json:
        print(json.dumps({
            "passed": res.passed,
            "error_count": len(res.errors),
            "warning_count": len(res.warnings),
            "errors": res.errors,
            "warnings": res.warnings,
            "output_path": res.output_path,
        }, indent=2))
    else:
        print(f"{'PASSED' if res.passed else 'FAILED'} "
              f"({len(res.errors)} errors, {len(res.warnings)} warnings)")
        for e in res.errors:
            print(f"  ERROR  {e}")
        for w in res.warnings:
            print(f"  warn   {w}")
        if res.output_path:
            print(f"Saved: {res.output_path}")
            print(PCBWAY_HANDOFF_NOTE)
        elif res.passed and not args.output:
            print("(no -o given; not saved)")
        else:
            print("Not saved (errors present).")

    return 0 if res.passed else 1


if __name__ == "__main__":
    raise SystemExit(_main())
